### ISSUE TITLE
Issues getting this working...

### ISSUE THREAD

**Issue by Ronald-Diemicke** [rmccue/Falcon#19]
So I think this was a really great find as it's supposed to do exactly what I'm trying to do... but unfortunately, I can't seem to get it to work. I'd be extremely greatful if you could share how this is supposed to work or to have some sort of instructions... one thing I did notice is that when I post on the fourm it seems to throw a 500 error... so I'm not sure if that's related.

**Comment by dtmunir** [comment]
I've followed all the instructions and set up a PostMark account, configured the incoming web hook and the server API. I've set up a google mailbox to forward emails to the Postmark inbound email address. PostMark is receiving my emails, but when it uses the webhook to post them to the plugin, i'm getting 500s:

```Inbound hook received HTTP 500```

Anybody know how to troubleshoot this? How can I find out the details of this 500 error? Where is the logging for this plugin? What are some of the reasons why the inbound hook doesn't seem to work when called from PostMark. When I try to load the inbound hook url in a browser, I get a "No input found" message.

**Comment by wkjones** [comment]
@dtmunir Were you able to resolve this? This is the exact same issue I am having. I know this was a while ago but any thoughts would be awesome.

**Comment by dtmunir** [comment]
Unfortunately not @wkjones - we gave up on that

**Comment by rmccue** [comment]
Apologies for never getting to this issue. Closing out as it's stale.
