### ISSUE TITLE
How to configure Mandrill?

### ISSUE THREAD

**Issue by archonic** [rmccue/Falcon#24]
Noob question here. How do I configure mandrill? I've got message handling set to mandrill, but I don't see anywhere (front-end or back) to enter API information.

**Comment by spacemano** [comment]
I have this issue too. The readme doesn't help.
When I try to send a test message Mandrill returns:
`Webhook failed with error: POST to http://MY-SITE.COM/wp-admin/admin-post.php?action=bbsub failed: Maximum (20) redirects followed`

Am I missing something? Thanks.

**Comment by rmccue** [comment]
Apologies for never getting to this issue. Closing out as it's stale.
