### ISSUE TITLE
Configuration issues

### ISSUE THREAD

**Issue by proseol** [rmccue/Falcon#26]
Hello,

I have installed and configured Mandrill correctly. This works and sends testing emails.
The second step I have installed bbPress-Reply-By-Email plugin. Also both vendors were downloaded and installed. The plugin is installing correctly. At the beginning there were an issue with Sputnik_Library_Plugin_Base at Autohooker line 105. I have changed Sputnik_Library_Plugin_Base to bbSubscriptions_Autohooker.
And now I am getting Exception error : "eAccelerator is configured to strip doc comments, cannot continue".
What should I do to make this working?
I have tried comment out the line 23 at Autohooker, where this makes this Exception, but I even cannot see the settings of the plugin (there should be "Send by Email" settings in settings menu in admin - and this is absent). 
Once I am trying to access to the settings directly by 
/wp-admin/options-general.php?page=bbsub_options
I am getting an error: You do not have sufficient permissions to access this page.

What can I do to fix this and make plugin working?

**Comment by rmccue** [comment]
Apologies for never getting to this issue. Closing out as it's stale.
