### ISSUE TITLE
White screen on install

### ISSUE THREAD

**Issue by yuenvision** [rmccue/Falcon#27]
Found this plugin via a Google search and also in the WP Plugin Search results. 
Installing resulted in a blank white screen (which I saw that another person also experienced).

Installation instructions on one of the forums said to download the repo and install via upload in the admin (which results in the same file structure as installing from WordPress admin).

Logs indicated that the issue was missing resources in the vendors directory. Downloading those resources and uploading them to their respective directories resolved the issue.

**Comment by gujingc** [comment]
Paul, what resources did you add? which directories?

**Comment by rmccue** [comment]
This is an extremely old issue, _but_ likely what happened was you download a zip without the submodules included. You need to use git to install the plugin. :)
