### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by joehoyle** [rmccue/Falcon#28]
- Whitespace is a bit lacking :) or generating formatting could maybe do with some cleanup
- Would be nice to use an external sheet for https://github.com/rmccue/bbPress-Reply-by-Email/blob/raptors-rule/library/Falcon/Manager.php#L37 perhaps.
- Missing the odd text domain such as https://github.com/rmccue/bbPress-Reply-by-Email/blob/raptors-rule/library/Falcon/Connector/WordPress.php#L682 
- Mixed spaces / tabs in https://github.com/rmccue/bbPress-Reply-by-Email/blob/raptors-rule/library/Falcon/Connector/bbPress.php maybe others too

I didn't actually run the code - but I don't see anything else obvious, I'd be happy to merge.

**Comment by rmccue** [comment]
Closing this; clearly the code passed review. ;)
