### ISSUE TITLE
Auto Add New Sites to Falcon

### ISSUE THREAD

**Issue by BronsonQuick** [rmccue/Falcon#30]
CAW!

I think new network sites should be automatically added to Falcon then users can opt out as required. Last night a new HM site was added for events and no one would get notifications until I added it in Network settings.

I'm totally cool if you think opt out is a bad option though :smile: 

CAW!

**Comment by Japh** [comment]
+1 for automatically adding new sites! I too wanted to get notifications for HM Events.

**Comment by rmccue** [comment]
It's up to whoever makes the new site to remember to add this one into there if they want it. I don't think auto-adding by default always makes sense, and adding a new pref wouldn't make much sense.

Could do it in a mu-plugin for the HM network?

(Also, removed your screenshot, keep in mind this is a public repo. :) )

**Comment by BronsonQuick** [comment]
Yeah let's go with MU then as admins won't remember to add it.

Yeah I didn't think anything was too private in that screenshot but fair call :smile: CAW!
