### ISSUE TITLE
Can't input any options in settings

### ISSUE THREAD

**Issue by emendesign** [rmccue/Falcon#31]
Hello,
I have been working on getting Falcon setting for bbpress and after I activate the plugin I simply get a no Mandrill API error as dashboard wide notification which is true but I have gone into settings to input it and there are no inputs for the API. There actually isn't anything there besides the message handler selector but it simply shows none as the only option.

![screencapture-wordpress-6509-14443-35771-cloudwaysapps-com-wp-admin-options-general-php-1431314439799](https://cloud.githubusercontent.com/assets/12388067/7558119/d8e4e8be-f762-11e4-980a-c60913c2ff0b.png)

I'm on the newest version of Wordpress 4.2.2

Let me know what I can do.

Thanks.

**Comment by rmccue** [comment]
It looks like something is conflicting with the plugin and causing the page to crash. Is there anything in your error log?

**Comment by emendesign** [comment]
Ok, so I fixed that problem but here is what I'm currently facing now.

I have setup my Mandrill Inbound routes but when I try to send a test I get this error.
Webhook failed with error: POST to http://talonpromotions.com/wp-admin/admin-post.php?action=bbsub failed with 500:

This is just a test domain with a cloned site that I'm using.

Here are my settings.
![screencapture-www-pb507-com-2015-05-med-city-movie-guy-review-avengers-1431352652172](https://cloud.githubusercontent.com/assets/12388067/7588648/00c1533c-f884-11e4-8fa5-b20949e571da.png)
![screencapture-www-pbsportscores-com-lacrosse-1428702457574](https://cloud.githubusercontent.com/assets/12388067/7588649/00c2edc8-f884-11e4-87a4-abbfee9600e0.png)

Let me know if you see any issues with my configuration.

Thanks.

**Comment by rmccue** [comment]
I think that's the wrong screenshot? :)

**Comment by emendesign** [comment]
I believe I updated them right after, can you try to refresh?

**Comment by rmccue** [comment]
Hmm. When you pulled down, is it possible you didn't pull subdomains as well?

Try `git submodule update --init --recursive`

**Comment by emendesign** [comment]
Yes, the two submodules are in there.

Here is what I'm getting in the logs.
[Tue May 12 17:35:51 2015] [error] [client 54.188.67.15] PHP Fatal error:  Uncaught exception 'Exception' with message 'Reply-to not formatted correctly' in /home/23582-14443.cloudwaysapps.com/nybpguhzvf/public_html/wp-content/plugins/Falcon/library/Falcon/Reply.php:82\nStack trace:\n#0 /home/23582-14443.cloudwaysapps.com/nybpguhzvf/public_html/wp-content/plugins/Falcon/library/Falcon/Handler/Mandrill.php(150): Falcon_Reply::parse_to('reply@talonprom...')\n#1 /home/23582-14443.cloudwaysapps.com/nybpguhzvf/public_html/wp-content/plugins/Falcon/library/Falcon.php(227): Falcon_Handler_Mandrill->handle_post()\n#2 [internal function]: Falcon::post_callback()\n#3 /home/23582-14443.cloudwaysapps.com/nybpguhzvf/public_html/wp-includes/plugin.php(496): call_user_func_array(Array, Array)\n#4 /home/23582-14443.cloudwaysapps.com/nybpguhzvf/public_html/wp-admin/admin-post.php(50): do_action('admin_post_nopr...')\n#5 {main}\n  thrown in /home/23582-14443.cloudwaysapps.com/nybpguhzvf/public_html/wp-content/plugins/Falcon/library/Falcon/Reply.php on line 82

**Comment by rmccue** [comment]
Interesting. Did you reply to an existing email, or did you send an email directly to the email address? Falcon only supports replying to posts, and needs the reply-to address from the email to authenticate your email message.

**Comment by emendesign** [comment]
I've only tried replying to a bbpress post so far. I should receive a notification as the post author, correct?

**Comment by emendesign** [comment]
I also tried to send a message to the reply email address and it did not seem to work.

**Comment by emendesign** [comment]
Hey, sorry to keep bugging you on this but any other ideas that you have that I could try?

**Comment by rmccue** [comment]
Apologies for never getting to this issue. Closing out as it's stale.
