### ISSUE TITLE
How to configure reply-to addresses with Postmark

### ISSUE THREAD

**Issue by bennypowers** [rmccue/Falcon#34]
Hi there,
I read the readme, but didn't understand two of the instructions:

> Set aside a domain to handle emails. notifications.example.com is a good example. We'll be sending emails from reply@ from this domain, and you'll be replying to the same email (but with a plus address bit for authentication).

where do i "set aside" this domain? in Postmark or with my hosting company (i.e. cpanel)?

I created a subdomain through cpanel 'notifications.jewishartistcenter.com' then set the Reply-To and From fields in Falcon settings to reply@notifications.jewishartistcenter.com. I get this error on submitting reply via the web

`Fatal error: Uncaught exception 'Exception' with message 'Error with sent body: {"ErrorCode":400,"Message":"Sender signature not defined for From address."}' in /home/gabrie37/public_html/jewishartistcenter.org/wp-content/plugins/Falcon-master/library/Falcon/Handler/Postmark.php:115 Stack trace: #0 /home/gabrie37/public_html/jewishartistcenter.org/wp-content/plugins/Falcon-master/library/Falcon/Handler/Postmark.php(89): Falcon_Handler_Postmark->send_single(Array) #1 /home/gabrie37/public_html/jewishartistcenter.org/wp-content/plugins/Falcon-master/library/Falcon/Connector/bbPress.php(134): Falcon_Handler_Postmark->send_mail(Array, Object(Falcon_Message)) #2 [internal function]: Falcon_Connector_bbPress->notify_on_reply(1038, 1026, 1004, 0, 4) #3 /home/gabrie37/public_html/jewishartistcenter.org/wp-includes/plugin.php(496): call_user_func_array(Array, Array) #4 /home/gabrie37/public_html/jewishartistcenter.org/wp-content/plugins/bbpress/includes/replies/functions.php(424): do_action('bbp_new_reply', 1038, 1026, 1004, 0, 4, in /home/gabrie37/public_html/jewishartistcenter.org/wp-content/plugins/Falcon-master/library/Falcon/Handler/Postmark.php on line 115`

(Note, i'm using a fix i got from a wpmudev dev in bbpress.php see my pull request)

**Comment by rmccue** [comment]
Apologies for never getting to this issue. Closing out as it's stale.
