### ISSUE TITLE
Problem after installing plugin

### ISSUE THREAD

**Issue by bpyne** [rmccue/Falcon#35]
Hi rmccue,

I installed your plugin, but after activating I have a problem with my site. Here is the error I am seeing. Have you seen anything like this before? Thanks in advance for any advice you can give.

Warning: require_once(E:\xampp\htdocs\ewkb\wp-content\plugins\Falcon-master/vendor/postmark-inbound/lib/Postmark/Autoloader.php): failed to open stream: No such file or directory in E:\xampp\htdocs\ewkb\wp-content\plugins\Falcon-master\library\Falcon\Handler\Postmark.php on line 9

Fatal error: require_once(): Failed opening required 'E:\xampp\htdocs\ewkb\wp-content\plugins\Falcon-master/vendor/postmark-inbound/lib/Postmark/Autoloader.php' (include_path='.;E:\xampp\php\PEAR') in E:\xampp\htdocs\ewkb\wp-content\plugins\Falcon-master\library\Falcon\Handler\Postmark.php on line 9

**Comment by BronsonQuick** [comment]
@bpyne You'll need to run `git clone --recursive git@github.com:rmccue/Falcon.git`as you're missing the submodules required for the plugin.

In case you're not familiar with git and just want a zip with all the files you need in it. I've uploaded one for you here: https://www.dropbox.com/s/c2udykiv1hqyvbu/falcon.zip?dl=0

Enjoy!

**Comment by bpyne** [comment]
Hi @BronsonQuick  

Thank you! Though I'm not sure how to upload the zip file now, I can't get to my site at all. I just get a page with that warning. Would it help if I tried to remove the plugin with FTP?

**Comment by bpyne** [comment]
Nevermind I think I figure it out.

**Comment by rmccue** [comment]
Apologies for never getting to this issue. Closing out as it's stale.
