### ISSUE TITLE
Add more info to the Active Sites list

### ISSUE THREAD

**Issue by johnbillion** [rmccue/Falcon#47]
I work at a company called Human Made. Naturally, we have more than one site on the network with the title Human Made. In fact, we have several sites that have identical titles.

This makes the Active Sites list under Network Admin -> Settings -> Falcon a little difficult to use. It would be nice if each site in the list displayed its domain name next to the title, or was linked to its admin area or site.

**Comment by rmccue** [comment]
> I work at a company called Human Made

Never heard of them.

> It would be nice if each site in the list displayed its domain name next to the title

Good point. The notification settings on the user edit screen does this (for just this reason), should do the same here.
