### ISSUE TITLE
Add a permalink to the top of each email

### ISSUE THREAD

**Issue by johnbillion** [rmccue/Falcon#48]
I work at a company called Human Made. Sometimes my colleagues have a good discussion in a thread, and by the time I've read Falcon's email thread for the first time there are already a bunch of replies, and at that point I prefer to read the discussion on the source site instead of in my email client so I can see the correct threading.

If a permalink was provided at the _top_ of each email, it would be easier to find and click it without having to do a lot of scrolling around in my email client.

**Comment by rmccue** [comment]
This was a design decision to match GitHub's notification style. Annoyingly, we can't add go-to-actions (#54) which would solve it.

Closing out.
