### ISSUE TITLE
Introduce a "New site" email with notification opt-out

### ISSUE THREAD

**Issue by johnbillion** [rmccue/Falcon#51]
When a new repo is created in an organisation that you're a member of on GitHub, an email gets sent out to you with a link to the repo and a link to immediately opt-out of notifications.

Falcon should introduce a similar email whenever a new site is created on the network.

**Comment by rmccue** [comment]
This is actually not part of Falcon, but rather part of the customisations we have on the HM network. Closing in favour of the (private) issue linked above.
