### ISSUE TITLE
The plugin brought our site down immediately

### ISSUE THREAD

**Issue by gujingc** [rmccue/Falcon#53]
As soon as we installed the plugin, our site went totally blank including the admin dashboard. We can not even debug.

We are using WordPress 5. Any suggestions? or the issue is known.

Jing

**Comment by rmccue** [comment]
Check your server's error logs, as they should record all fatal errors there.

As this isn't a bug/feature request, closing out, but you can still comment if needed. :)

**Comment by gujingc** [comment]
Just to confirm, the fatal error is not caused by the plugin but maybe some server setting conflict, correct?

**Comment by rmccue** [comment]
I can't say exactly why you're getting a fatal error, but it's more likely to be a server misconfiguration than an issue in the plugin. (We'd have likely noticed the error already!)

**Comment by gujingc** [comment]
Roger, we are very interested in this solution. We also found that you have published it with Wordpress.org. Great you are doing that.

We are trying to access the link: https://postviamail.unicornis.pl/configuration/

Questions:

1) Does this only work with Postmark or it accepts other transactional mail services?

2) We read that to make it compatible with the current version of WordPress, we need to add the following code: / ADDED replystring and modified the wp_mail call to make the reply to address show up in the email body
$replystring = ‘To reply to the forum, click on this link: ?subject=’.$subj.'” target=”_top”>Reply To Forum‘;
wp_mail( $to, $subj, nl2br($replystring.”\r\n\n”.$data.”\r\n\n”.$replystring.$notices[$user->ID]), $header, $attachments );

3) if we want to add the following:
- When someone replies to a Forum thread via email, our system will first check if the email is registered with our site. If not, the site will send an email inviting the person to register.
- If the user is registered with us, then the system will check if the person belongs to a premium membership. If not, the system will invite the person to sign up with that membership.

To achieve the functions described in 3, do we need to modify codes in your plugin? or we can achieve it without touching the codes in your plugin? 

Thanks a million.

Jing

**Comment by gujingc** [comment]
We are trying to set up the DNS records. What did we do wrong on cName:

See our screenshots:
https://drive.google.com/file/d/1kqiMcDvg5_uExtWutUYyvzwCuA3O7PlU/view?usp=sharing
https://drive.google.com/file/d/1JvVBbksV37JmqBbP0HeV7oSFCkNCRpJ_/view?usp=sharing
