### ISSUE TITLE
Add gmail go-to-actions markup to view on site links.

### ISSUE THREAD

**Issue by peterwilsoncc** [rmccue/Falcon#54]
Gmail allows email authors to include view action markup to emails to show a shortcut link in the subject:

![Inbox__1__-_peter_humanmade_com_-_Human_Made_Mail](https://user-images.githubusercontent.com/519727/54897246-b91e6900-4f1b-11e9-9486-efb657120d0d.png)

It'd be handy to include this markup for the "View on site" links in the footer of each email, it's available as JSON-LD or microdata.

Reference: https://developers.google.com/gmail/markup/reference/go-to-action#view_action
Related #48

**Comment by rmccue** [comment]
This is actually already implemented in a separate plugin we run on the HM website (check the source, however unfortunately you need to meet volume requirements for email to have this enabled. It's unlikely that Falcon sites will ever meet this requirement.
